version: "3.7"

services:
  backend:
    build:
      context: ./backend
    container_name: melamart_backend
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - 5000
    networks: 
      - backend_network
  frontend:
    build:
      context: ./frontend
    container_name: melamart_frontend
    restart: unless-stopped
    env_file: 
      - .env
    environment: 
      - PORT=3000
    ports:
      - 3000
    networks: 
      - backend_network
  
  webserver: 
    image: nginx:1.19
    container_name: webserver_nginx
    restart: unless-stopped
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - backend
      - frontend
    networks: 
      - backend_network

networks: 
  backend_network:
